import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/nav/Navbar";
import Footer from "@/components/common/nav/Footer";
import Footertwo from "@/components/common/nav/Footertwo";
import { AuthProvider } from "./Provider";
// import { usePathname } from "next/navigation";
// import { useEffect, useRef } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // const path = usePathname();
  // const headerRef = useRef(null);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <Navbar />
          {children}
        </AuthProvider>

        {/* {path === "/" ? <Footer /> : <Footertwo />} */}
      </body>
    </html>
  );
}
